#!/usr/bin/perl

BEGIN {
   $|=1;
   use CGI::Carp('fatalsToBrowser');
}

#open(STDOUT, "| tee c:/seeii/log/creator.log STDOUT");
open(STDOUT, ">>c:/seeii/log/creator.log") or die "Cannot open LOGFILE for WRITING: $!";
open(STDERR, ">&STDOUT") or die "Cannot open LOGFILE for WRITING: $!";

  my $process_log_file = "c:/seeii/process/log.txt";
  open(PLFILE, ">>$process_log_file") or warn "Cannot open $process_log_file for WRITING: $!";
  my $process_log = " Start - " . localtime() . "   Creator \n";
  print PLFILE $process_log;
  close(PLFILE);

# This program will delete all the unaccessable urls that have null add_date.
# This program will delete the urls from all the tables.
# In the end, it will update the unaccessable_url_tab with the current timestamp as the add date.

  use DBI;

  my $ulfile = "C:/seeii/common/urllist.txt";

  my $db   = "index_db";
  my $host = "localhost";
  my $port = "3306";
  my $dbh  = DBI->connect("DBI:mysql:database=$db;host=$host;port=$port","root", "password")
            or die "Couldn't connect to database: " . DBI->errstr;

  my $create_1  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.ACCEPTKEYWORD_TAB (KEYWORD VARCHAR(150) NOT NULL UNIQUE, PRIMARY KEY (KEYWORD)) ENGINE = INNODB"); 
  my $create_2  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.TOSCAN_TAB (KEYWORD VARCHAR(150) NOT NULL UNIQUE, ADD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, LAST_SCANNED_DATE TIMESTAMP, PRIMARY KEY (KEYWORD)) ENGINE = INNODB");
  my $create_3  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.DOMAIN_TAB (DOMAIN_ID INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE, DOMAIN VARCHAR(200) NOT NULL UNIQUE, ACCEPT CHAR(1), IPADDRESS VARCHAR(20), COUNTRY CHAR(2), PRIMARY KEY (DOMAIN_ID), INDEX (DOMAIN)) ENGINE = INNODB AUTO_INCREMENT = 1");
  my $create_4  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.URL_LIST_TAB (URL VARCHAR(300) NOT NULL UNIQUE, ACCEPT CHAR(1), FORCE_IND CHAR(1), TYPE_OF_URL CHAR(1), ADD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, SOURCE CHAR(1) NOT NULL DEFAULT 'A', PRIMARY KEY (URL)) ENGINE = INNODB"); 
  my $create_5  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.URL_TAB (URL_ID INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE, URL VARCHAR(300) NOT NULL UNIQUE, ADD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, SIZE DECIMAL(10,2) UNSIGNED, CONTENT_DIGEST_ID VARCHAR(50), LAST_UPDATED_DATE INT, LAST_READ_DATE TIMESTAMP, LAST_PARSED_DATE TIMESTAMP, DOMAIN_ID INT UNSIGNED, LAST_LINKRANK_UPDATED_DATE TIMESTAMP, QUALIFIED_FOR_LINK CHAR(1), TYPE_OF_URL CHAR(1), PRIMARY KEY (URL_ID), INDEX (URL), INDEX (CONTENT_DIGEST_ID), INDEX (DOMAIN_ID), FOREIGN KEY (DOMAIN_ID) REFERENCES DOMAIN_TAB (DOMAIN_ID)) ENGINE=INNODB AUTO_INCREMENT = 1");
  my $create_6  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.URL_REJECTED_TAB (URL VARCHAR(300) NOT NULL UNIQUE, REJECTED_DATE TIMESTAMP, REJECTED_REASON TINYINT, PRIMARY KEY (URL)) ENGINE = INNODB");
  my $create_7  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.URL_BACKLINK_TAB (URL_ID_TO INT UNSIGNED NOT NULL, URL_ID_FROM INT UNSIGNED NOT NULL, PRIMARY KEY (URL_ID_TO, URL_ID_FROM), FOREIGN KEY (URL_ID_TO) REFERENCES URL_TAB (URL_ID), FOREIGN KEY (URL_ID_FROM) REFERENCES URL_TAB (URL_ID)) ENGINE = INNODB");
  my $create_8  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.WORD_TAB (WORD_ID INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE, WORD VARCHAR(200) NOT NULL, LANGUAGE TINYINT NOT NULL DEFAULT 0, SOUNDEX CHAR(10) NOT NULL DEFAULT ' ', LAST_LINKRANK_UPDATED_DATE TIMESTAMP, LAST_RANK_UPDATED_DATE TIMESTAMP, TOTAL_PAGES INT, PRIMARY KEY (WORD_ID), INDEX (WORD), UNIQUE INDEX (LANGUAGE, WORD), INDEX (SOUNDEX)) ENGINE = INNODB AUTO_INCREMENT = 1");
  my $create_9  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.WORD_LINK_TAB (WORD_ID INT UNSIGNED NOT NULL, URL_ID_TO INT UNSIGNED NOT NULL, URL_ID_FROM INT UNSIGNED NOT NULL, PRIMARY KEY (WORD_ID, URL_ID_TO, URL_ID_FROM), FOREIGN KEY (WORD_ID) REFERENCES WORD_TAB (WORD_ID), FOREIGN KEY (URL_ID_TO) REFERENCES URL_TAB (URL_ID), FOREIGN KEY (URL_ID_FROM) REFERENCES URL_TAB (URL_ID)) ENGINE = INNODB");
  my $create_a  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.CONTENT_TAB (CONTENT_DIGEST_ID VARCHAR(50) NOT NULL UNIQUE, URL_ID INT UNSIGNED NOT NULL UNIQUE, CONTENT TEXT, META_DATA TEXT, HEADR1 TEXT, HEADR2 TEXT, HEADR3 TEXT, ALT_DATA TEXT, TOTAL_UNIQUE_WORDS INT, PRIMARY KEY (URL_ID), INDEX (CONTENT_DIGEST_ID), FOREIGN KEY (URL_ID) REFERENCES URL_TAB (URL_ID)) ENGINE = INNODB");
  my $create_b  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.TITLE_DESC_TAB (URL_ID INT UNSIGNED NOT NULL, TITLE VARCHAR(100) NOT NULL, META_DESC TEXT NOT NULL, PRIMARY KEY (URL_ID), FOREIGN KEY (URL_ID) REFERENCES URL_TAB (URL_ID)) ENGINE = INNODB");
  my $create_c  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.READ_URL_TAB (URL_ID INT UNSIGNED NOT NULL, ADD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, QUEUE_NUM TINYINT, PRIMARY KEY (URL_ID), FOREIGN KEY (URL_ID) REFERENCES URL_TAB (URL_ID)) ENGINE = INNODB");
  my $create_d  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.UNACCESSABLE_URL_TAB (URL VARCHAR(300) NOT NULL UNIQUE, LAST_TRIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD_DATE TIMESTAMP, PRIMARY KEY (URL)) ENGINE = INNODB");
  my $create_e  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.PARSE_URL_TAB (URL_ID INT UNSIGNED NOT NULL, ADD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, QUEUE_NUM TINYINT, PRIMARY KEY (URL_ID), FOREIGN KEY (URL_ID) REFERENCES URL_TAB (URL_ID)) ENGINE = INNODB");
  my $create_f  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.URL_DUPLICATE_TAB (URL_ID_1 INT UNSIGNED NOT NULL, URL_ID_2 INT UNSIGNED NOT NULL, ADD_DATE TIMESTAMP, PRIMARY KEY (URL_ID_1, URL_ID_2), FOREIGN KEY (URL_ID_1) REFERENCES URL_TAB (URL_ID), FOREIGN KEY (URL_ID_2) REFERENCES URL_TAB (URL_ID)) ENGINE = INNODB");
  my $create_g  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.SPAM_URL_TAB (URL VARCHAR(300) NOT NULL UNIQUE, ADD_DATE TIMESTAMP, PRIMARY KEY (URL)) ENGINE = INNODB");
  my $create_h  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.URL_LINKRANK_TAB (URL_ID INT UNSIGNED NOT NULL UNIQUE, LINKRANK DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0, PRIMARY KEY (URL_ID), FOREIGN KEY (URL_ID) REFERENCES URL_TAB (URL_ID)) ENGINE = MYISAM");
  my $create_i  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.WORD_LINKRANK_TAB (WORD_ID INT UNSIGNED NOT NULL, URL_ID INT UNSIGNED NOT NULL, LINKRANK DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0, PRIMARY KEY (WORD_ID, URL_ID), FOREIGN KEY (WORD_ID) REFERENCES WORD_TAB (WORD_ID), FOREIGN KEY (URL_ID) REFERENCES URL_TAB (URL_ID)) ENGINE = MYISAM");
  my $create_j  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.WORD_COUNT_RANK_TAB (WORD_ID INT UNSIGNED NOT NULL, URL_ID INT UNSIGNED NOT NULL, WORD_COUNT INT NOT NULL DEFAULT 0, META_COUNT INT NOT NULL DEFAULT 0, HEADR_COUNT INT NOT NULL DEFAULT 0, ALT_COUNT INT NOT NULL DEFAULT 0, URL_COUNT INT NOT NULL DEFAULT 0, PRIMARY KEY (WORD_ID, URL_ID), FOREIGN KEY (WORD_ID) REFERENCES WORD_TAB (WORD_ID), FOREIGN KEY (URL_ID) REFERENCES URL_TAB (URL_ID)) ENGINE = MYISAM");
  my $create_k  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.WORD_RANK_TAB (WORD_ID INT UNSIGNED NOT NULL, URL_ID INT UNSIGNED NOT NULL, RANK DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0, PRIMARY KEY (WORD_ID, URL_ID), INDEX (WORD_ID), FOREIGN KEY (WORD_ID) REFERENCES WORD_TAB (WORD_ID), FOREIGN KEY (URL_ID) REFERENCES URL_TAB (URL_ID)) ENGINE = MYISAM");
  my $create_l  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.DOMAIN_REJECTED_TAB (DOMAIN VARCHAR(200) NOT NULL UNIQUE, REJECTED_DATE TIMESTAMP, REJECTED_REASON TINYINT, PRIMARY KEY (DOMAIN)) ENGINE = INNODB");
  my $create_m  = $dbh->prepare_cached("CREATE TABLE INDEX_DB.WORD_LANG_TAB (WORD_SOUND VARCHAR(200) NOT NULL, WORD_LANG VARCHAR(200) NOT NULL UNIQUE, LANGUAGE TINYINT NOT NULL, INDEX (WORD_SOUND)) ENGINE = INNODB");

  my $load_url_list = $dbh->prepare("LOAD DATA INFILE '$ulfile' IGNORE INTO TABLE URL_LIST_TAB FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' (URL, ACCEPT)");

  print localtime() . " - CREATE started\n";
  my $pid = $$;
  print "     Process Id = $pid \n";

  $create_1->execute();
  $create_2->execute();
  $create_3->execute();
  $create_4->execute();
  $create_5->execute();
  $create_6->execute();
  $create_7->execute();
  $create_8->execute();
  $create_9->execute();
  $create_a->execute();
  $create_b->execute();
  $create_c->execute();
  $create_d->execute();
  $create_e->execute();
  $create_f->execute();
  $create_g->execute();
  $create_h->execute();
  $create_i->execute();
  $create_j->execute();
  $create_k->execute();
  $create_l->execute();
  $create_m->execute();

  my $success = $load_url_list->execute();

  print " Total number of URL List Records = $success \n";

  $dbh->disconnect;

  print localtime() . " - CREATE ended\n";

  open(PLFILE, ">>$process_log_file") or warn "Cannot open $process_log_file for WRITING: $!";
  $process_log = " Close - " . localtime() . "   Creator \n";
  print PLFILE $process_log;
  close(PLFILE);

  my $command = "perl lister.pl"; 

  exec "$command"; 

  exit;

